### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by erichegonzales** [learn-co-curriculum/phase-0-css-fundamentals-lab#11]
### Canvas Link

https://learning.flatironschool.com/courses/5729/assignments/179059?module_item_id=395767

### Concern

The previous CSS lesson sections did not prepare well for this lab

### Suggested Changes

Add more lessons on the deliverables before the lab or have this lab be a walk-through of each step

**Comment by lizbur10** [comment]
Hi @erichegonzales ! Thank you for bringing this to our attention. I have made note of your comment and it will be addressed in the next update to the CSS section.

Thanks for contributing to the Flatiron School curriculum 💙
