### ISSUE TITLE
Canvas does not reflect completed labs

### ISSUE THREAD

**Issue by pekellogg** [learn-co-curriculum/phase-0-css-fundamentals-lab#3]
Hello,

Thanks for your help with my issue. 

Ever since the platform migration from learn.co to Canvas for the online, self-paced SE program, I've noticed that Canvas inconsistently reflects completed labs via the green checkmark. My concern is that I won't be able to tell which modules I've completed at a Canvas module-level glance or will need to do manual work to prove 95% completion of this program. For a temporary work-around, I've been submitting lab links manually via Canvas instead of thru CLI.

I fork, clone locally, and push to my github account by following the instructions included in each lab's readme. (git add . **>** git commit -m "message" **>** git push). I've confirmed that this pushes my local work to my repo.

Let me know if I can provide any more info to help troubleshoot.

![canvas_ui_module-lvl](https://user-images.githubusercontent.com/71993048/131763350-7eedacee-053c-4dec-af53-68cdca129a19.png)
![completed_github_repo](https://user-images.githubusercontent.com/71993048/131763352-8f36ad40-05eb-4f37-ab1e-039a9152c29e.png)
![canvas_ui](https://user-images.githubusercontent.com/71993048/131763354-6d6b6ca6-6f71-4aa6-9772-42606453c45e.png)

**Comment by graciemcguire** [comment]
Hi @pekellogg ! First, I spoke with the education team, and we are not holding students to the 95% completion mark anymore, so hopefully that alleviates some stress for you! Second, the way the prework is set up is a bit different than the rest of our curriculum. Once you start phase 1 (and onwards) you won't need to follow the `git add` , `git commit -m ""` , `git push` steps anymore.
Hope this helps!
