### ISSUE TITLE
CSS lab

### ISSUE THREAD

**Issue by davidhcho1095** [learn-co-curriculum/phase-0-css-fundamentals-lab#7]
unacceptable that the lesson just tells you to google how to implement CSS elements into the HTML document. The whole point of the prework is to teach you the basics before you start the actual curriculum and it's incredibly lazy to not tell students how to do but to just google how to implement attributes.

**Comment by lizbur10** [comment]
Hello @davidhcho1095 - thank you for providing feedback on this issue. I'm sorry to hear that this was frustrating for you. 

The majority of your learning as you move through the program will come directly from Flatiron materials and instructors/lecturers, but using Google to find out how to accomplish something is also a very important skill for a developer.  Learning how to construct a search query and identify good sources of information in search results is a learned skill, and requires practice like all other developer skills. For this reason, while most of the information you need to complete assignments and labs is in the lessons, you will also occasionally encounter instructions to research an issue using search tools.

I'm going to go ahead and close this issue, but we will make note of your feedback and take it into consideration in the next round of updates to the materials.

Thanks for contributing to the Flatiron School curriculum. 💙
